<?php
echo "<br>";
echo "<div class='container-fluid'>";
echo 	"<div class='row align-items-center justify-content-center'>";
echo 		"<div class='col-md-8'>";
echo "<hr>";
echo 			"<div class='row'>";
echo 				"<div class='col-md-6' >";
echo 					"<div class='card'>";
echo						"<img class='card-img-top' src='../images/botica.jpg'></img>";
echo 					"</div>";
echo 				"</div>";
echo 				"<div class='col-md-6' >";
echo 					"<div class='card'>";
echo						"<div class='card-header card-title'>";
echo 							"<h4 class='text-center'>Botica - Farmácia de Manipulação e Drogaria</h4>";
echo 						"</div>";
echo 						"<div class='card-body'>";
echo 							"<p class='spacing'>Localizada na cidade de Rio Grande, Rio Grande do Sul, Brasil, a farmácia Botica iniciou suas atividades dia 16 de outubro de 2001, encontrando-se no mercado há mais de 15 anos.</p>";
echo 						"</div>";
echo 					"</div>";
echo 					"<hr>";
echo 					"<div class='card'>";
echo						"<div class='card-header card-title'>";
echo 							"<h4 class='text-center'>Informações para Contato</h4>";
echo 						"</div>";
echo 						"<div class='card-body'>";
echo         					"<p>Endereço: Rua Andradas, 247 | Bairro Centro | CEP: 96200-030 | Rio Grande, RS </p>";
echo 					        "<p>E-mail: boticariogrande@outlook.com</p><p>Telefones: (53) 3231-9551, (53) 3233-2750 e (53) 3236-2703</p>";
echo 						"</div>";
echo 					"</div>";
echo 				"</div>";
echo 			"</div>";
echo 		"</div>";
echo 	"</div>";
echo "</div>";
