<?php
// falta o teste da sessão...
echo "<br>";
echo "<div class='container-fluid'>";
echo 	"<div class='row align-items-center justify-content-center'>";
echo 		"<div class='col-md-8'>";
echo 			"<div class='card'>";
echo 				"<div class='card-header'>";
echo 					"<h4>Categorias</h4>";
echo 				"</div>";
echo 				"<div class='card-body'>";
echo 					"<div class='row'>";
echo 					"<div class='col-md-4'>";
echo 					"<div class='card' style='width: 20rem;'>";
echo 						"<img class='card-img-top' src='../images/fitos.jpg' alt='Card image cap'>";
echo   						"<div class='card-body'>";
echo  		   					"<h4 class='card-title text-center'>Fitoterápicos</h4>";
echo  		   						"<p class='card-text text-justify'>Um medicamento fitoterápico é aquele alcançado de plantas medicinais, onde utiliza-se exclusivamente derivados de droga vegetal tais como: suco, cera, exsudato, óleo, extrato, tintura, entre outros. O termo confunde-se com fitoterapia ou com planta medicinal que realmente envolve o vegetal como um todo no exercício curativo e/ou profilático.</p>";
echo 							"<button type='button' class='btn btn-default btn-lg'>";
echo   								"<span class='	glyphicon glyphicon-star' aria-hidden='true'></span> Editar";
echo 							"</button> ";
echo 							" <button type='button' class='btn btn-default btn-lg'>";
echo   								"<span class='	glyphicon glyphicon-star' aria-hidden='true'></span> Excluir";
echo 							"</button>";
echo 					"</div></div>";
echo 				"</div>";
echo 					"<div class='col-md-4'>";
echo 					"<div class='card' style='width: 20rem;'>";
echo 						"<img class='card-img-top' src='../images/fitos.jpg' alt='Card image cap'>";
echo   						"<div class='card-body'>";
echo  		   					"<h4 class='card-title text-center'>Fitoterápicos</h4>";
echo  		   						"<p class='card-text text-justify'>Um medicamento fitoterápico é aquele alcançado de plantas medicinais, onde utiliza-se exclusivamente derivados de droga vegetal tais como: suco, cera, exsudato, óleo, extrato, tintura, entre outros. O termo confunde-se com fitoterapia ou com planta medicinal que realmente envolve o vegetal como um todo no exercício curativo e/ou profilático.</p>";
echo 							"<button type='button' class='btn btn-default btn-lg'>";
echo   								"<span class='	glyphicon glyphicon-star' aria-hidden='true'></span> Editar";
echo 							"</button> ";
echo 							" <button type='button' class='btn btn-default btn-lg'>";
echo   								"<span class='	glyphicon glyphicon-star' aria-hidden='true'></span> Excluir";
echo 							"</button>";
echo 					"</div></div>";
echo 				"</div>";
echo 					"<div class='col-md-4'>";
echo 					"<div class='card' style='width: 20rem;'>";
echo 						"<img class='card-img-top' src='../images/fitos.jpg' alt='Card image cap'>";
echo   						"<div class='card-body'>";
echo  		   					"<h4 class='card-title text-center'>Fitoterápicos</h4>";
echo  		   						"<p class='card-text text-justify'>Um medicamento fitoterápico é aquele alcançado de plantas medicinais, onde utiliza-se exclusivamente derivados de droga vegetal tais como: suco, cera, exsudato, óleo, extrato, tintura, entre outros. O termo confunde-se com fitoterapia ou com planta medicinal que realmente envolve o vegetal como um todo no exercício curativo e/ou profilático.</p>";
echo 							"<button type='button' class='btn btn-default btn-lg'>";
echo   								"<span class='	glyphicon glyphicon-star' aria-hidden='true'></span> Editar";
echo 							"</button> ";
echo 							" <button type='button' class='btn btn-default btn-lg'>";
echo   								"<span class='	glyphicon glyphicon-star' aria-hidden='true'></span> Excluir";
echo 							"</button>";
echo 					"</div></div>";
echo 				"</div>";

echo 				"</div>";
echo 				"</div>";
echo 			"</div>";
echo 		"</div>";
echo "</div>";